name: Hello

on:
  push:
    branches: [main]

jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: "Now it is"
        run: |
          date
      - name: Directory content
        run: |
          ls -l
